name: Export Slack Logs to CSV

on:
  schedule:
    - cron: '0 0 1 * *'  # 毎月1日の00:00に実行
  workflow_dispatch:      # 手動実行も可能

jobs:
  export-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build
        
      - name: Export to CSV and upload to GitHub Pages
        run: npm run export:csv:github
        env:
          INPUT_SLACKTOKEN: ${{ secrets.SLACK_TOKEN }}
          INPUT_TIMEZONE: 'Asia/Tokyo'
          INPUT_GOOGLECLIENTEMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          INPUT_GOOGLEPRIVATEKEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          INPUT_FOLDERID: ${{ secrets.FOLDER_ID }}
          INPUT_AUTOJOIN: 'true'
          INPUT_LASTDAYS: '30'
          NODE_OPTIONS: '--openssl-legacy-provider'
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PAGES_BRANCH: 'gh-pages'
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Create gh-pages branch if not exists
        run: |
          if ! git ls-remote --heads origin gh-pages | grep gh-pages; then
            git checkout --orphan gh-pages
            git rm -rf .
            echo "# Slack Logs CSV Export" > README.md
            git add README.md
            git commit -m "Initial gh-pages commit"
            git push origin gh-pages
          fi
